## 配置文件



# 备份配置
backup:
  enable: 0                       # 是否启用备份
  backup_dir: "./backups"         # 备份根目录路径（支持相对路径和绝对路径）

# 重试配置（全局设置）
retry:
  enabled: 1                      # 是否启用任务级重试（1启用，0禁用）
  delay_minutes: 3               # 重试间隔时间（分钟），默认10分钟
  max_attempts: 3                 # 最大重试次数，默认3次
  task_timeout_minutes: 15        # 任务超时时间（分钟），超时后自动终止任务并触发重试

# 机器人配置列表
# webhooks:
#   奖励池名单发布:    "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=338f6d2c-3457-4b48-b7d2-fd60f4db98f4"
#   看板自动发布:      "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a9d5a3ce-9091-4f99-94f1-c80832238c1a"
#   运营转化数据播报:   "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=fa2847ba-1291-49c9-ae5d-0acd9712c220"
#   激励播报（内部）:   "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=3b052688-8964-446a-bd5f-12c5716ca152"
#   激励播报:          "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=7ad929e6-8953-43fd-bead-c13d90d32740"
#   续航组看板播报:     "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a6cb134d-7167-4dfa-b49b-04fb4e77d544"
#   澳新数据看板:       "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=57b436ca-c037-4b8d-9136-5f7580efdc7f"
#   澳新激励发布:       "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=778808a4-2ffc-44ad-aed2-0bfee021bd80"
#   AP&研学数据播报:    "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=686ad22f-8943-462c-8be8-4a1160df0af5"
#   约课数据看板:      "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=3afd2ff7-8d7c-42c8-8a47-1bfe86c68a2d"


test_webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ee57f939-0e4e-4707-beba-422dae91538e"
error_webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=833b098e-d8b8-43ea-bfdf-cade0d040fb6"
upload_url_template: "https://qyapi.weixin.qq.com/cgi-bin/webhook/upload_media?key={key}&type=file"

tasks:

#-----------------------------------------   task 0 多webhook示例  --------------------------------------     
  - name: "学员明细自动播报"
    excel_path: "C:/Users/EDY/OneDrive - PPLINGO PTE LTD/自动播报文件/学员明细备份.xlsx"
    # 多个webhook配置，每个可独立设置times、capture_configs、send_file_enable
    webhooks:
      - webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=833b098e-d8b8-43ea-bfdf-cade0d040fb6"
        name: "学员明细"
        times: ["07:02", "09:02", "11:02", "13:02", "15:02", "17:02", "19:02", "21:02", "23:52"]
        capture_configs:
          - sheet_name: "昨日课量备份"
            range: E1
            name: "test_webhook1"
        send_file_enable: 1  # 可选，未配置默认为0

      - webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ee57f939-0e4e-4707-beba-422dae91538e"
        name: "学员明细自动播报"
        times: ["07:30", "09:30", "11:30", "13:30", "15:30", "17:02", "19:02", "21:02", "23:52"]
        capture_configs:
          - sheet_name: "昨日课量备份"
            range: E1
            name: "test_webhook2"
        send_file_enable: 0  # 可选，未配置默认为0


#-----------------------------------------   task 0 多webhook示例  --------------------------------------     
  - name: "往期顺次"
    excel_path: "C:/Users/EDY/OneDrive - PPLINGO PTE LTD/CN-CC Management Team-08-中文业绩数据（内部） - 文档/数据看板/线索-工作簿2026-当月往期+顺次1.xlsx"
    # 多个webhook配置，每个可独立设置times、capture_configs、send_file_enable
    webhooks:
      - webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=833b098e-d8b8-43ea-bfdf-cade0d040fb6"
        name: "往期顺次"
        times: ["08:35","10:35", "12:35", "14:35", "16:35", "18:35", "20:35", "22:00"]
        capture_configs:
          - sheet_name: "总览页面"
            range: AE1
            name: "总览页面"
        send_file_enable: 0  # 可选，未配置默认为0

    


  #   # 发送文件
  #   send_file_enable: 0
  #   # 数据校验
  #   data_check:
  #     check_sheet: "团队"
  #     check_range: "L5"
  #     check_frequency: 3
  #     notify_message: "数据校验失败，请检查"
  #     notify_users: ["hezhengsong","zhufuzhe"]
  #     warning_webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=833b098e-d8b8-43ea-bfdf-cade0d040fb6"




# 当前程序只能保证excel端刷新完成，如果数仓数据未处理完，无法判断




# 每次刷新失败重试时都发发送通知，三次刷新失败后发送通知，并在10分钟后再次开始此任务，并发送通知，时间可配置   高优先级
#命令行任务列表与完成情况展示，任务列表。
# 检测文件大小，配置了发送文件但大于20M的发送通知