## 配置文件

# Webhook地址
# "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=338f6d2c-3457-4b48-b7d2-fd60f4db98f4"   奖励池名单发布
# "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a9d5a3ce-9091-4f99-94f1-c80832238c1a"   看板自动发布
# "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=833b098e-d8b8-43ea-bfdf-cade0d040fb6"   报错提醒
# "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ee57f939-0e4e-4707-beba-422dae91538e"   测试Bot


excel_path: "C:/Users/EDY/Desktop/BOT_TEST/excel文件/奖励池名单.xlsx"     # 截图文件路径
file_path: "C:/Users/EDY/Desktop/BOT_TEST/excel文件/奖励池名单.xlsx"      # 发送文件路径
webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ee57f939-0e4e-4707-beba-422dae91538e" #测试Bot
upload_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/upload_media?key=ee57f939-0e4e-4707-beba-422dae91538e&type=file" #测试Bot
#是否发送文件
send_file: 1

capture_ranges:
  - file_path: "C:/Users/EDY/Desktop/BOT_TEST/excel文件/奖励池名单.xlsx" # 截图文件路径
    sheet_name: "入池名单"
    name: "奖励池名单"
    range: "A1:D33"
  - file_path: "C:/Users/EDY/Desktop/BOT_TEST/excel文件/奖励池名单.xlsx" # 截图文件路径
    sheet_name: "日期校验"
    name: "日期校验"
    range: "B1:E3"
  


schedule:
  enabled: 0
  times:
    - "00:00"
    - "00:30"
    - "01:00"
    - "01:30"
    - "02:00"
    - "02:30"
    - "03:00"
    - "03:30"
    - "04:00"
    - "04:30"
    - "05:00"
    - "05:30"
    - "06:00"
    - "06:30"
    - "07:00"
    - "07:30"
    - "08:00"
    - "08:30"
    - "09:00"
    - "09:30"
    - "10:00"
    - "10:05"
    - "10:10"
    - "10:15"
    - "10:20"
    - "10:25"
    - "10:30"
    - "10:35"
    - "10:40"
    - "10:45"
    - "10:50"
    - "10:55"
    - "11:00"
    - "11:05"
    - "11:10"
    - "11:15"
    - "11:20"
    - "11:25"
    - "11:30"
    - "11:35"
    - "11:40"
    - "11:45"
    - "11:50"
    - "11:55"
    - "12:00"
    - "12:05"
    - "12:10"
    - "12:15"
    - "12:20"
    - "12:25"
    - "12:30"
    - "12:35"
    - "12:40"
    - "12:45"
    - "12:50"
    - "12:55"
    - "13:00"
    - "13:05"
    - "13:10"
    - "13:15"
    - "13:20"
    - "13:25"
    - "13:30"
    - "13:35"
    - "13:40"
    - "13:45"
    - "13:50"
    - "13:55"
    - "14:00"
    - "14:05"
    - "14:10"
    - "14:15"
    - "14:20"
    - "14:25"
    - "14:30"
    - "14:35"
    - "14:40"
    - "14:45"
    - "14:50"
    - "14:55"
    - "15:00"
    - "15:05"
    - "15:10"
    - "15:15"
    - "15:20"
    - "15:25"
    - "15:30"
    - "15:35"
    - "15:40"
    - "15:45"
    - "15:50"
    - "15:55"
    - "16:00"
    - "16:05"
    - "16:10"
    - "16:15"
    - "16:20"
    - "16:25"
    - "16:30"
    - "16:35"
    - "16:40"
    - "16:45"
    - "16:50"
    - "16:55"
    - "17:00"
    - "17:05"
    - "17:10"
    - "17:15"
    - "17:20"
    - "17:25"
    - "17:30"
    - "17:35"
    - "17:40"
    - "17:45"
    - "17:50"
    - "17:55"
    - "18:00"
    - "18:05"
    - "18:10"
    - "18:15"
    - "18:20"
    - "18:25"
    - "18:30"
    - "18:35"
    - "18:40"
    - "18:45"
    - "18:50"
    - "18:55"
    - "19:00"
    - "19:05"
    - "19:10"
    - "19:15"
    - "19:20"
    - "19:25"
    - "19:30"
    - "19:35"
    - "19:40"
    - "19:45"
    - "19:50"
    - "19:55"
    - "20:00"
    - "20:30"
    - "21:00"
    - "21:30"
    - "22:00"
    - "22:30"
    - "23:00"
    - "23:30"


    






# v1.0.0 版本更新日志
# 1. 定时任务功能，可以设置每天的定时发送时间点
# 2. 多区域截图功能，可以设置多个截图区域，并分别命名(当前仅支持一个sheet)
# 3. 发送消息的功能，可以将截图通过bot发送到指定的微信群聊（当前仅支持一个bot）
# 4. 支持打开Excel文件时自动刷新数据

# 2025.5.14
# 截图区域：支持多个sheet截图，支持多个区域截图
# 发送消息：支持多种消息格式（文本、图片、文件等）

# 2025.5.22
# 数据日期校验，如果数据日期不在范围内，则不发送消息，并且@指定人员，等待下次发送
# 发送文件时可自定义文件名

# 更新计划:
# 日志：记录机器人推送消息记录，包括时间、发布群聊、消息内容等，保存到本地文件
# 内存管理：优化内存管理，避免内存泄漏长时间运行
# 程序自动重启：如果程序崩溃，自动重启程序
# 刷新超时：如果刷新数据超时，自动重试3次
# 发送失败重试：如果发送失败，自动重试3次


# 多个文件：支持多个文件同时使用，支持不同的文件路径
# 支持多个机器人：支持多个机器人同时使用，支持不同的微信群聊
# 权限控制：限制机器人仅限特定群聊使用，其他群聊无法使用
# @机器人发送一次日报


#报错
#'NoneType' object has no attribute 'RefreshAll'
#[错误] Excel操作异常：This COM object can not automate the makepy process - please run makepy manually for this object



#已解决
# module 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x9' has no attribute 'CLSIDToClassMap'